apiVersion: source.toolkit.fluxcd.io/v1  
kind: GitRepository  
metadata:  
  name: instavote  
  namespace: flux-system  
spec:  
  interval: 30s  
  ref:  
    branch: main  
  url: https://github.com/pjunwei95/instavote-deploy.git 
